branch-defaults:
  default:
    environment: null
    group_suffix: null
  main:
    environment: flask-env
    group_suffix: null
global:
  application_name: CMSC495_Project_API_v1
  branch: null
  default_ec2_keyname: aws_key
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
